# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/86198/Desktop/vivadoProject/DD_Project/constraints.xdc

# IP: ip/st_g/st_g.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==st_g || ORIG_REF_NAME==st_g} -quiet] -quiet

# IP: ip/background_1/background.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==background || ORIG_REF_NAME==background} -quiet] -quiet
