# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/86198/Desktop/vivadoProject/DD_Project/PopStar/PopStar.srcs/sources_1/ip/st_r/st_r.xci
# IP: The module: 'st_r' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/86198/Desktop/vivadoProject/DD_Project/PopStar/PopStar.gen/sources_1/ip/st_r/st_r_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'st_r'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/86198/Desktop/vivadoProject/DD_Project/PopStar/PopStar.srcs/sources_1/ip/st_r/st_r.xci
# IP: The module: 'st_r' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/86198/Desktop/vivadoProject/DD_Project/PopStar/PopStar.gen/sources_1/ip/st_r/st_r_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'st_r'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
